---
title: "032_SOK1005_V23_final"
format: pdf
editor: visual
---

Assignment 1: reading static webpages

```{r}
rm(list = ls())
library(tidyverse)
library(ggplot2)
library(readr)
library(data.table)
library(reshape2)
```

```{r}
# 1. download the four dataseries

lower_Trop <- read_table("http://vortex.nsstc.uah.edu/data/msu/v6.0/tlt/uahncdc_lt_6.0.txt")
mid_Trop <- read_table("http://vortex.nsstc.uah.edu/data/msu/v6.0/tmt/uahncdc_mt_6.0.txt")
trop <- read_table("http://vortex.nsstc.uah.edu/data/msu/v6.0/ttp/uahncdc_tp_6.0.txt")
low_Strat <- read_table("http://vortex.nsstc.uah.edu/data/msu/v6.0/tls/uahncdc_ls_6.0.txt")
```

```{r}
# 2. Using only the Global temperature calculate the yearly moving average for each dataseries.

lower_Trop <- 
  lower_Trop %>% 
  filter(Year %in% c(1978:2022)) %>% 
  group_by(Year) %>% 
  summarize("Lower Troposphere" = mean(as.numeric(Globe))) %>% 
  ungroup()

mid_Trop <- 
  mid_Trop %>% 
  filter(Year %in% c(1978:2022)) %>% 
  group_by(Year) %>% 
  summarize("Mid Troposphere" = mean(as.numeric(Globe))) %>% 
  ungroup()

trop <- 
  trop %>% 
  filter(Year %in% c(1978:2022)) %>% 
  group_by(Year) %>% 
  summarize("Tropopause" = mean(as.numeric(Globe))) %>% 
  ungroup()

low_Strat <- 
  low_Strat %>% 
  filter(Year %in% c(1978:2022)) %>% 
  group_by(Year) %>% 
  summarize("Lower Stratosphere" = mean(as.numeric(Globe))) %>% 
  ungroup()
```

```{r}
# Making a new list with the different athmospheric locations together

rolling_mean <- 
  
  list(lower_Trop, 
       mid_Trop, 
       trop, 
       low_Strat) %>% 
  
  reduce(full_join, 
         by = "Year")
```

```{r}
# 3. Calculate a new variable called Average averageing the four locations

rolling_mean$Average <- 
  rowMeans(rolling_mean[, c(2:5)])
```

```{r}
# Makes it readable for ggplot to get all variables & filters from 1980
rolling_mean_m <- rolling_mean %>% 
  select(!"Average") %>% 
  filter(Year>=1980) %>% 
  melt(id.var="Year")
```

```{r}
# 4. Make a plot of the four athmosphere locations and their average in the same plot, only using data from 1980 and onwards

plot <- 
  ggplot()+
  geom_line(data=rolling_mean_m, aes(x=as.numeric(Year), y=value, group=1), color="#999999") + 
  geom_point(data=rolling_mean_m, aes(x=as.numeric(Year), y=value, group=1, color=variable))+
  geom_line(data=rolling_mean, aes(x=as.numeric(Year), y=Average, group=1, color="Yearly average across all layers"))+
  ggtitle("Departure from Avg Temperature, 1980-2022")+
  ylab("Departure from Avg. (deg C)")+
  xlab("Year")+
  scale_color_manual(values=c("#56cde9", "#56B4E9", "#008cc6", "#005679", "red"), name="")+
  theme_minimal()+
  theme(legend.position="bottom",
        legend.text=element_text(size=7))

plot
```
